### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by gilesknap** [gilesknap/kubecon2024-talk#1]
@coretl @GDYendell I would appreciate a quick review of this if you have time.
https://github.com/gilesknap/kubecon2024-talk/blob/main/cfp.md
Thanks!

**Comment by coretl** [comment]
Looks good to me!

**Comment by GDYendell** [comment]
Looks good. If you meant to tag Chris in the Open Source Projects section I don't think it worked.

**Comment by gilesknap** [comment]
Thanks both. The tag was just for him to read.
